name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]


    steps:
    # checkout codebase
    - uses: actions/checkout@v2

    # install python
    - name: Setup Python ${{ matrix.python-version }}
      uses: action/setup-python@vs
      with:
        python-version: ${{ matrix.python-version }}

    # install python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;

    # run actual unit tests
    - name: Test with unittest
      run: |
        python -m unittest tests.test_root
